url: https://minhchaublog.github.io
baseurl: /blog/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
     path: ""
     type: "pages"
   values:
     permalink: "/blog/"